import { Icon } from '@iconify/react';
import React, { createContext, useEffect, useState } from 'react'
import Category from './Category';

// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface ICategories {
  category: string;
  packs:    Pack[];
  warning?: Warning;
}

export interface Pack {
  name:         string;
  display:      string;
  version:      string;
  description:  string;
  incompatible: string[];
  lastupdated:  number;
  video:        string;
  requires?:    string[];
}

export interface Warning {
  text:  string;
  color: string;
}

export const Context = createContext<{
  selected: {[key: string]: Pack[]},
  setSelected: (selected: {[key: string]: Pack[]}) => void,
  hover: Pack | null,
  setHover: (hover: Pack|null) => void,
}>({
  selected: {},
  setSelected: () => {},
  hover: null,
  setHover: () => {},
});

function Datapacks() {
  const [data, setData] = useState<ICategories[]>([])
  const [selected, setSelected] = useState<{[key: string]: Pack[]}>({});
  const [hover, setHover] = useState<Pack | null>(null);

  useEffect(() => {
    fetch('https://cors-anywhere.thecodeblog.net/vanillatweaks.net/assets/resources/json/1.18/dpcategories.json')
      .then(response => response.json())
      .then(data => setData(data.categories))
  }, [])

  return (
    <Context.Provider value={{
      selected, setSelected, hover, setHover,
    }}>
      
      <div className="flex h-full gap-8">
        <div className="flex-1 h-full mr-0 pb-16 flex flex-col">
          <div className="min-w-0 m-8 mb-12 mr-0 overflow-scroll bg-[#696969] rounded-lg shadow-lg p-8">
            <div className="flex items-center justify-between">
              <h1 className="text-2xl text-white tracking-widest">Datapacks</h1>
            </div>
            <div className="min-w-0 overflow-auto flex flex-col gap-2 mt-8">
                {data.length > 0 && data.map((category, index) => (
                  <Category category={category} index={index} />
                ))}
            </div>
          </div>
        </div>
        <div className="w-72 m-8 mb-28 gap-4 flex flex-col overflow-hidden flex-shrink-[9999] position-relative ml-0">
          <div className="w-full flex-1 bg-[#696969] shadow-lg rounded-lg overflow-hidden flex flex-col">
            <div className="p-4 bg-[#E99743] flex items-center gap-3 text-white text-lg">
              <div className="w-6 h-8 flex items-center justify-center">
                <Icon icon="uil:align-center-v" className="w-6 h-6" />
              </div>
              <span className="block truncate">Datapack Selector</span>
            </div>
            <div className="flex-1 p-4 overflow-auto h-max flex flex-col gap-4">
              {Object.entries(selected).map(([category, packs]) => (
                <div className="flex flex-col gap-2">
                  <h2 className="text-xl text-white flex items-center gap-2">
                    <Icon icon="uil:direction" className="w-6 h-6 flex-shrink-0" />
                    {category}
                  </h2>
                  <div className="flex flex-col gap-2">
                    {packs.map(pack => (
                      <div className="flex items-center gap-2 ml-6 text-white">
                        <Icon icon="uil:direction" className="w-6 h-6 flex-shrink-0" />
                        <img src={`https://vanillatweaks.net/assets/resources/icons/datapacks/1.18/${pack.name}.png`} alt={pack.name} className="w-4 h-4" />
                        <span className="block truncate">{pack.display}</span>
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <a href="/installation" className="w-full flex items-center justify-center bg-[#E99743] text-white rounded-md py-3">How to Install</a>
            <a href="/installation" className="w-full flex bg-[#E94D43] items-center justify-center text-white rounded-md py-3 relative">
              <Icon icon="mdi:patreon" className="text-white absolute left-0 top-1/2 -translate-y-1/2 w-6 h-6 ml-3" />
              Support Us
            </a>
          </div>
        </div>
      </div>
    </Context.Provider>
  )
}

export default Datapacks
